use petshop
db.createCollection('mammals')
db.mammals.insert({name:'dabour',species:'canis familiaris'})
db.mammals.insert({name:'Alzation',species:'canis familiaris'})
db.mammals.insert({name:'Rot weiler',species:'canis familiaris'})
db.mammals.insert({name:'Manos Catery',species:'Felis Catus'})
db.mammals.insert({name:'Balinese',species:'Felis Catus'})
db.mammals.insert({name:'Bengal',species:'Felis Catus'})
db.mammals.insert({name:'Kiskky',species:'Agpornis'})
db.mammals.insert({name:'Moko',species:'Agpornis'})
db.mammals.insert({name:'Bubbles',species:'Agpornis'})
db.mammals.find()
